/*
	Defines user info
*/

define({
	name: "Oliver",
	friends:[ 		
		{name: "Cris"},  
		{name: "India"},  
		{name: "Renata"},  
		{name: "Inger"},  
		{name: "Catharine"},  
		{name: "Rina"},  
		{name: "Kaley"},  
		{name: "Marian"},  
		{name: "Kathyrn"},  
		{name: "Emerson"},  
		{name: "Amada"},  
		{name: "Debera"},  
		{name: "Yoshiko"},  
		{name: "Craig"},  
		{name: "Hana"},  
		{name: "Tomiko"},  
		{name: "Belia"},  
		{name: "Stephenie"},  
		{name: "Johnson"},  
		{name: "Eusebia"},  
		{name: "Jewel"},  
		{name: "Maryjane"},  
		{name: "Cliff"},  
		{name: "Donny"},  
		{name: "Sheridan"},  
		{name: "Carmelita"},  
		{name: "Domitila"},  
		{name: "Willene"},  
		{name: "Maude"},  
		{name: "Marchelle"},  
		{name: "Lanora"},  
		{name: "Ronni"},  
		{name: "Windy"},  
		{name: "Jackqueline"},  
		{name: "Johnathan"},  
		{name: "Cody"},  
		{name: "Robena"},  
		{name: "Tonita"},  
		{name: "Christoper"},  
		{name: "Daniella"},  
		{name: "Maybell"},  
		{name: "Savanna"},  
		{name: "Riley"},  
		{name: "Len"},  
		{name: "Lesley"},  
		{name: "Melvina"},  
		{name: "Tarah"},  
		{name: "Sheree"},  
		{name: "Joy"},  
		{name: "Santana"}
	]

});